using System.Collections.Generic;
using Godot;

namespace SlotTheory.Core;

/// <summary>
/// Draws procedural tree/rock props generated by MapGenerator.
/// Kept intentionally low-contrast so combat readability stays high.
/// </summary>
public partial class MapDecorationLayer : Node2D
{
    private readonly struct DecorationVisual
    {
        public DecorationVisual(Vector2 position, DecorationType type, float scale, float phase, float tint)
        {
            Position = position;
            Type = type;
            Scale = scale;
            Phase = phase;
            Tint = tint;
        }

        public Vector2 Position { get; }
        public DecorationType Type { get; }
        public float Scale { get; }
        public float Phase { get; }
        public float Tint { get; }
    }

    private readonly List<DecorationVisual> _decorations = new();
    private float _time;
    private bool _reducedMotion;

    public void Initialize(DecorationData[] decorations, int seed)
    {
        _decorations.Clear();

        var rng = new RandomNumberGenerator();
        uint seedBits = unchecked((uint)seed);
        rng.Seed = seedBits == 0 ? 1u : seedBits;

        foreach (var decoration in decorations)
        {
            float scale = decoration.Type == DecorationType.Tree
                ? rng.RandfRange(0.82f, 1.26f)
                : rng.RandfRange(0.78f, 1.18f);

            float phase = rng.RandfRange(0f, Mathf.Tau);
            float tint = rng.RandfRange(0.88f, 1.12f);

            _decorations.Add(new DecorationVisual(decoration.Pos, decoration.Type, scale, phase, tint));
        }

        _decorations.Sort((a, b) => a.Position.Y.CompareTo(b.Position.Y));
        SyncReducedMotion();
        QueueRedraw();
    }

    public override void _Process(double delta)
    {
        bool changed = SyncReducedMotion();
        if (_reducedMotion)
        {
            if (changed)
                QueueRedraw();
            return;
        }

        _time += (float)delta * (MobileOptimization.IsMobile() ? 0.7f : 1f);
        QueueRedraw();
    }

    public override void _Draw()
    {
        foreach (var decoration in _decorations)
        {
            if (decoration.Type == DecorationType.Tree)
                DrawTree(decoration);
            else
                DrawRock(decoration);
        }
    }

    private void DrawTree(DecorationVisual decoration)
    {
        Vector2 root = decoration.Position;
        float s = decoration.Scale;
        float tint = decoration.Tint;

        float sway = _reducedMotion
            ? 0f
            : Mathf.Sin(_time * 1.45f + decoration.Phase) * (1.65f * s);

        float pulse = _reducedMotion
            ? 1f
            : 0.88f + 0.12f * Mathf.Sin(_time * 2.15f + decoration.Phase * 1.6f);

        Vector2 trunkBase = root + new Vector2(0f, 7f * s);
        Vector2 trunkTop = root + new Vector2(sway * 0.35f, -8f * s);
        DrawLine(trunkBase, trunkTop, new Color(0.10f * tint, 0.08f * tint, 0.14f * tint, 0.82f), 2.2f * s);

        Vector2 crown = root + new Vector2(sway, -12f * s);
        var outer = new Color(0.09f * tint, 0.28f * tint, 0.20f * tint, 0.72f * pulse);
        var mid = new Color(0.12f * tint, 0.36f * tint, 0.26f * tint, 0.78f * pulse);
        var core = new Color(0.22f * tint, 0.56f * tint, 0.40f * tint, 0.82f * pulse);

        DrawCircle(crown + new Vector2(0f, 2f * s), 11f * s, outer);
        DrawCircle(crown + new Vector2(-5f * s, 5f * s), 8f * s, mid);
        DrawCircle(crown + new Vector2(5f * s, 5f * s), 8f * s, mid);
        DrawCircle(crown + new Vector2(0f, 3f * s), 5.1f * s, core);

        DrawCircle(crown + new Vector2(0f, 1f * s), 15f * s, new Color(0.20f * tint, 0.90f * tint, 0.65f * tint, 0.05f * pulse));
        DrawCircle(root + new Vector2(0f, 9f * s), 7f * s, new Color(0f, 0f, 0f, 0.14f));
    }

    private void DrawRock(DecorationVisual decoration)
    {
        Vector2 p = decoration.Position;
        float s = decoration.Scale;
        float tint = decoration.Tint;

        float pulse = _reducedMotion
            ? 1f
            : 0.92f + 0.08f * Mathf.Sin(_time * 1.75f + decoration.Phase);

        var rock = new[]
        {
            p + new Vector2(-11f * s,  3f * s),
            p + new Vector2( -8f * s, -6f * s),
            p + new Vector2(  0f * s, -10f * s),
            p + new Vector2(  9f * s, -5f * s),
            p + new Vector2( 12f * s,  3f * s),
            p + new Vector2(  4f * s,  9f * s),
            p + new Vector2( -6f * s,  8f * s),
        };

        var baseColor = new Color(0.16f * tint, 0.13f * tint, 0.22f * tint, 0.86f);
        var edgeColor = new Color(0.30f * tint, 0.26f * tint, 0.42f * tint, 0.66f);
        DrawPolygon(rock, new[] { baseColor });

        var highlight = new[]
        {
            p + new Vector2(-6f * s, -3f * s),
            p + new Vector2( 0f * s, -7f * s),
            p + new Vector2( 5f * s, -4f * s),
            p + new Vector2(-1f * s, -1f * s),
        };
        DrawPolygon(highlight, new[] { new Color(0.40f * tint, 0.35f * tint, 0.55f * tint, 0.52f * pulse) });

        for (int i = 0; i < rock.Length; i++)
        {
            Vector2 from = rock[i];
            Vector2 to = rock[(i + 1) % rock.Length];
            DrawLine(from, to, edgeColor, 1.2f * s);
        }

        DrawCircle(p + new Vector2(0f, 10f * s), 8f * s, new Color(0f, 0f, 0f, 0.12f));
        DrawCircle(p + new Vector2(0f, 0f), 13f * s, new Color(0.35f * tint, 0.55f * tint, 0.95f * tint, 0.045f * pulse));
    }

    private bool SyncReducedMotion()
    {
        bool reducedMotion = SettingsManager.Instance?.ReducedMotion ?? false;
        bool changed = reducedMotion != _reducedMotion;
        _reducedMotion = reducedMotion;
        return changed;
    }
}
