using System.Collections.Generic;
using Godot;

namespace SlotTheory.Core;

/// <summary>
/// Draws procedural synthwave props generated by MapGenerator (crystal spikes and anomaly nodes).
/// Kept intentionally low-contrast so combat readability stays high.
/// </summary>
public partial class MapDecorationLayer : Node2D
{
    private readonly struct DecorationVisual
    {
        public DecorationVisual(Vector2 position, DecorationType type, float scale, float phase, float tint)
        {
            Position = position;
            Type = type;
            Scale = scale;
            Phase = phase;
            Tint = tint;
        }

        public Vector2 Position { get; }
        public DecorationType Type { get; }
        public float Scale { get; }
        public float Phase { get; }
        public float Tint { get; }
    }

    private readonly struct DiagonalLine
    {
        public DiagonalLine(Vector2 start, Vector2 end, Color color, float width, float phase, float speed)
        {
            Start = start; End = end; Color = color; Width = width; Phase = phase; Speed = speed;
        }

        public Vector2 Start { get; }
        public Vector2 End   { get; }
        public Color   Color { get; }
        public float   Width { get; }
        public float   Phase { get; }
        public float   Speed { get; }
    }

    // Neon palette for diagonal fault lines (hue, no alpha -- applied at draw time).
    private static readonly Color[] DiagPalette =
    {
        new(0.00f, 0.90f, 1.00f),   // cyan
        new(1.00f, 0.10f, 0.88f),   // magenta
        new(0.55f, 0.10f, 1.00f),   // violet
        new(1.00f, 0.60f, 0.00f),   // amber
        new(1.00f, 0.15f, 0.50f),   // hot-pink
    };

    private readonly List<DiagonalLine>   _diagonals  = new();
    private readonly List<DecorationVisual> _decorations = new();
    private float _time;
    private bool _reducedMotion;

    // Map bounds used for diagonal line pivot sampling.
    private const float MapLeft   = 0f;
    private const float MapRight  = MapGenerator.COLS * MapGenerator.CELL_W;
    private const float MapTop    = MapGenerator.GRID_Y;
    private const float MapBottom = MapGenerator.GRID_Y + MapGenerator.ROWS * MapGenerator.CELL_H;
    private const float MapCx     = (MapLeft + MapRight)  * 0.5f;
    private const float MapCy     = (MapTop  + MapBottom) * 0.5f;

    public void Initialize(DecorationData[] decorations, int seed)
    {
        _decorations.Clear();
        _diagonals.Clear();

        var rng = new RandomNumberGenerator();
        uint seedBits = unchecked((uint)seed);
        rng.Seed = seedBits == 0 ? 1u : seedBits;

        foreach (var decoration in decorations)
        {
            float scale = decoration.Type == DecorationType.Tree
                ? rng.RandfRange(0.82f, 1.26f)
                : rng.RandfRange(0.78f, 1.18f);

            float phase = rng.RandfRange(0f, Mathf.Tau);
            float tint = rng.RandfRange(0.88f, 1.12f);

            _decorations.Add(new DecorationVisual(decoration.Pos, decoration.Type, scale, phase, tint));
        }

        _decorations.Sort((a, b) => a.Position.Y.CompareTo(b.Position.Y));
        GenerateDiagonals(rng);
        SyncReducedMotion();
        QueueRedraw();
    }

    private void GenerateDiagonals(RandomNumberGenerator rng)
    {
        // 3-5 line groups, each 1-2 parallel lines offset slightly apart.
        int groupCount = rng.RandiRange(3, 5);

        // Angle biases seeded per map: two dominant directions (adds coherence across groups).
        float biasA = rng.RandfRange(Mathf.DegToRad(22f), Mathf.DegToRad(65f));
        float biasB = biasA + rng.RandfRange(Mathf.DegToRad(28f), Mathf.DegToRad(55f));

        for (int g = 0; g < groupCount; g++)
        {
            // Alternate between the two dominant angles with small noise, occasionally use a wild angle.
            float baseAngle = rng.Randf() < 0.80f
                ? (g % 2 == 0 ? biasA : biasB) + rng.RandfRange(-Mathf.DegToRad(12f), Mathf.DegToRad(12f))
                : rng.RandfRange(Mathf.DegToRad(15f), Mathf.DegToRad(75f));

            // Pivot somewhere across the visible map area.
            float px = rng.RandfRange(MapLeft + 80f, MapRight - 80f);
            float py = rng.RandfRange(MapTop  + 40f, MapBottom - 40f);
            var pivot = new Vector2(px, py);

            // Direction vector; extend 2 000 px each side -- always spans the map.
            var dir = new Vector2(Mathf.Cos(baseAngle), Mathf.Sin(baseAngle));
            const float Reach = 2000f;
            var lineStart = pivot - dir * Reach;
            var lineEnd   = pivot + dir * Reach;

            var baseColor = DiagPalette[rng.RandiRange(0, DiagPalette.Length - 1)];
            float baseAlpha = rng.RandfRange(0.07f, 0.16f);
            float width = rng.RandfRange(0.9f, 2.2f);
            float phase = rng.RandfRange(0f, Mathf.Tau);
            float speed = rng.RandfRange(0.35f, 0.80f);

            // Primary line.
            _diagonals.Add(new DiagonalLine(
                lineStart, lineEnd,
                new Color(baseColor, baseAlpha),
                width, phase, speed));

            // ~55 % chance of a companion line (parallel, slight offset) for a hazard-stripe read.
            if (rng.Randf() < 0.55f)
            {
                var perp   = new Vector2(-dir.Y, dir.X);
                float gap  = rng.RandfRange(5f, 14f);
                float aOff = rng.RandfRange(-0.06f, 0.06f);
                _diagonals.Add(new DiagonalLine(
                    lineStart + perp * gap, lineEnd + perp * gap,
                    new Color(baseColor, baseAlpha * rng.RandfRange(0.55f, 0.85f)),
                    width * rng.RandfRange(0.5f, 0.85f),
                    phase + aOff, speed));
            }
        }
    }

    public override void _Process(double delta)
    {
        bool changed = SyncReducedMotion();
        if (_reducedMotion)
        {
            if (changed)
                QueueRedraw();
            return;
        }

        _time += (float)delta * (MobileOptimization.IsMobile() ? 0.7f : 1f);
        QueueRedraw();
    }

    public override void _Draw()
    {
        DrawDiagonals();
        foreach (var decoration in _decorations)
        {
            if (decoration.Type == DecorationType.Tree)
                DrawTree(decoration);
            else
                DrawRock(decoration);
        }
    }

    private void DrawDiagonals()
    {
        foreach (var line in _diagonals)
        {
            float pulse = _reducedMotion
                ? 1f
                : 0.65f + 0.35f * Mathf.Sin(_time * line.Speed + line.Phase);

            var c = new Color(line.Color, line.Color.A * pulse);
            DrawLine(line.Start, line.End, c, line.Width);
        }
    }

    // Crystal spike -- replaces organic tree. Neon magenta/cyan pylon with animated tip glow.
    private void DrawTree(DecorationVisual decoration)
    {
        Vector2 root = decoration.Position;
        float s = decoration.Scale;
        float tint = decoration.Tint;

        float pulse = _reducedMotion
            ? 1f
            : 0.80f + 0.20f * Mathf.Sin(_time * 2.3f + decoration.Phase);

        float flicker = _reducedMotion
            ? 1f
            : 0.92f + 0.08f * Mathf.Sin(_time * 5.7f + decoration.Phase * 2.1f);

        // Crystal body: tall narrow diamond with two flanking sub-spikes.
        float bodyH = 22f * s;
        float bodyW = 5.5f * s;
        var bodyPts = new[]
        {
            root + new Vector2(       0f,  -bodyH),        // apex
            root + new Vector2( bodyW,     -bodyH * 0.38f), // right shoulder
            root + new Vector2( bodyW * 0.6f, 5f * s),     // right base
            root + new Vector2(       0f,   8f * s),        // base centre
            root + new Vector2(-bodyW * 0.6f, 5f * s),     // left base
            root + new Vector2(-bodyW,    -bodyH * 0.38f), // left shoulder
        };

        // Left sub-spike
        float subH = 13f * s;
        float subW = 3.2f * s;
        var leftSpike = new[]
        {
            root + new Vector2(-bodyW * 0.4f, -bodyH * 0.55f),
            root + new Vector2(-bodyW * 0.4f - subW, -bodyH * 0.55f + subH * 0.35f),
            root + new Vector2(-bodyW * 0.4f,         -bodyH * 0.55f + subH),
        };
        var rightSpike = new[]
        {
            root + new Vector2( bodyW * 0.4f, -bodyH * 0.55f),
            root + new Vector2( bodyW * 0.4f + subW, -bodyH * 0.55f + subH * 0.35f),
            root + new Vector2( bodyW * 0.4f,         -bodyH * 0.55f + subH),
        };

        // Colors: deep violet body, bright magenta edge, cyan core facet
        var bodyFill  = new Color(0.22f * tint, 0.05f, 0.38f * tint, 0.80f);
        var bodyEdge  = new Color(0.80f * tint, 0.15f, 0.95f * tint, 0.70f * flicker);
        var subFill   = new Color(0.18f * tint, 0.04f, 0.30f * tint, 0.72f);
        var coreFacet = new Color(0.40f * tint, 0.80f, 1.00f,         0.55f * pulse);

        // Inner cyan facet (front face of crystal)
        var facetPts = new[]
        {
            root + new Vector2(  0f,    -bodyH * 0.96f),
            root + new Vector2( bodyW * 0.55f, -bodyH * 0.30f),
            root + new Vector2(  0f,           -bodyH * 0.04f),
            root + new Vector2(-bodyW * 0.55f, -bodyH * 0.30f),
        };

        DrawPolygon(bodyPts,   new[] { bodyFill });
        DrawPolygon(leftSpike, new[] { subFill });
        DrawPolygon(rightSpike,new[] { subFill });
        DrawPolygon(facetPts,  new[] { coreFacet });

        // Outline edges
        for (int i = 0; i < bodyPts.Length; i++)
            DrawLine(bodyPts[i], bodyPts[(i + 1) % bodyPts.Length], bodyEdge, 1.1f * s);

        // Apex glow + faint ground shadow
        float glowR = (4.5f + 2.5f * (pulse - 0.80f) / 0.20f) * s;
        DrawCircle(root + new Vector2(0f, -bodyH), glowR,
            new Color(0.85f * tint, 0.30f, 1.00f, 0.55f * pulse * flicker));
        DrawCircle(root + new Vector2(0f, -bodyH), glowR * 1.9f,
            new Color(0.60f * tint, 0.10f, 0.80f, 0.14f * pulse));
        DrawCircle(root + new Vector2(0f, 9f * s), 7f * s,
            new Color(0.50f, 0.00f, 0.70f, 0.10f));
    }

    // Anomaly node -- replaces organic rock. Hexagonal neon terminal with pulsing core indicator.
    private void DrawRock(DecorationVisual decoration)
    {
        Vector2 p = decoration.Position;
        float s = decoration.Scale;
        float tint = decoration.Tint;

        float pulse = _reducedMotion
            ? 1f
            : 0.75f + 0.25f * Mathf.Sin(_time * 1.9f + decoration.Phase);

        float flicker = _reducedMotion
            ? 1f
            : 0.90f + 0.10f * Mathf.Sin(_time * 6.3f + decoration.Phase * 1.8f);

        // Flat hexagon body
        float r = 9.5f * s;
        var hex = new Vector2[6];
        for (int i = 0; i < 6; i++)
        {
            float a = Mathf.Pi / 6f + i * Mathf.Pi / 3f;   // flat-top orientation
            hex[i] = p + new Vector2(Mathf.Cos(a), Mathf.Sin(a)) * r;
        }

        // Inner smaller hex for the "circuit board" inset
        float ri = r * 0.58f;
        var hexInner = new Vector2[6];
        for (int i = 0; i < 6; i++)
        {
            float a = Mathf.Pi / 6f + i * Mathf.Pi / 3f;
            hexInner[i] = p + new Vector2(Mathf.Cos(a), Mathf.Sin(a)) * ri;
        }

        var bodyFill  = new Color(0.08f * tint, 0.04f, 0.18f * tint, 0.88f);
        var insetFill = new Color(0.05f * tint, 0.03f, 0.12f * tint, 0.82f);
        var edgeColor = new Color(0.20f * tint, 0.85f, 0.90f * tint, 0.60f * flicker);  // cyan rim
        var spokeColor= new Color(0.15f * tint, 0.70f, 0.80f * tint, 0.28f * pulse);

        DrawPolygon(hex,      new[] { bodyFill });
        DrawPolygon(hexInner, new[] { insetFill });

        // Hex outlines
        for (int i = 0; i < 6; i++)
        {
            DrawLine(hex[i],      hex[(i + 1) % 6],      edgeColor, 1.0f * s);
            DrawLine(hexInner[i], hexInner[(i + 1) % 6], spokeColor, 0.7f * s);
        }

        // Radial spokes from inner hex vertices to outer hex vertices
        for (int i = 0; i < 6; i++)
            DrawLine(hexInner[i], hex[i], spokeColor, 0.6f * s);

        // Pulsing core dot -- amber/gold to signal "active" state
        float coreR = 2.8f * s * pulse;
        DrawCircle(p, coreR * 1.8f, new Color(1.00f, 0.60f, 0.00f, 0.18f * pulse));
        DrawCircle(p, coreR,        new Color(1.00f, 0.75f, 0.10f, 0.85f * pulse * flicker));

        // Ambient glow beneath
        DrawCircle(p, r * 1.55f, new Color(0.10f * tint, 0.65f, 0.75f * tint, 0.055f * pulse));
    }

    private bool SyncReducedMotion()
    {
        bool reducedMotion = SettingsManager.Instance?.ReducedMotion ?? false;
        bool changed = reducedMotion != _reducedMotion;
        _reducedMotion = reducedMotion;
        return changed;
    }
}
